In [5]:
def convert_units(value, from_unit, to_unit):
    conversions = {
        "m_to_ft": 3.28084,
        "ft_to_m": 1 / 3.28084,
        "kg_to_lbs": 2.20462,
        "lbs_to_kg": 1 / 2.20462,
        "L_to_gal": 0.264172,
        "gal_to_L": 1 / 0.264172
    }

    key = f"{from_unit}_to_{to_unit}"

    if key in conversions:
        return value * conversions[key]
    else:
        raise ValueError("Unsupported conversion")

def main():
    try:
        print("Select conversion type:")
        print("1. Length (m <-> ft)")
        print("2. Weight (kg <-> lbs)")
        print("3. Volume (L <-> gal)")

        choice = input("Enter 1, 2, or 3: ").strip()

        if choice == "1":
            from_unit = input("Convert from (m/ft): ").strip().lower()
            to_unit = "ft" if from_unit == "m" else "m"
        elif choice == "2":
            from_unit = input("Convert from (kg/lbs): ").strip().lower()
            to_unit = "lbs" if from_unit == "kg" else "kg"
        elif choice == "3":
            from_unit = input("Convert from (L/gal): ").strip().lower()
            to_unit = "gal" if from_unit == "L" else "L"
        else:
            print("Invalid choice!")
            return

        value = float(input("Enter the value to convert: "))
        result = convert_units(value, from_unit, to_unit)
        print(f"Converted value: {result:.4f} {to_unit}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception:
        print("An unexpected error occurred. Please try again.")

if __name__ == "__main__":
    main()

Select conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter 1, 2, or 3: 2
Convert from (kg/lbs): kg
Enter the value to convert: 2
Converted value: 4.4092 lbs


In [6]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The average of the numbers.
    """
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Find the maximum number in a list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The maximum number.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum number in a list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The minimum number.
    """
    return min(numbers)

def main():
    try:
        print("Select an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter 1, 2, 3, or 4: ").strip()
        operation_map = {"1": calculate_sum, "2": calculate_average, "3": find_maximum, "4": find_minimum}

        if choice not in operation_map:
            print("Invalid choice!")
            return

        numbers_input = input("Enter a list of numbers separated by spaces: ").strip()
        numbers = [float(num) for num in numbers_input.split()]

        if not numbers:
            print("Error: No numbers entered.")
            return

        result = operation_map[choice](numbers)
        print(f"Result: {result:.4f}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception:
        print("An unexpected error occurred. Please try again.")

if __name__ == "__main__":
    main()

Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 4
Enter a list of numbers separated by spaces: 2
Result: 2.0000


In [ ]:
def extract_every_other(lst):

    return lst[::2]

lst = [1, 2, 3, 4, 5, 6]
print("Every other element:", extract_every_other(lst))

Every other element: [1, 3, 5]


In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage:
print("Sublist (2 to 4):", get_sublist(lst, 2, 4))

Sublist (2 to 4): [3, 4, 5]


In [ ]:
def reverse_list(lst):

    return lst[::-1]

# Example usage:
print("Reversed list:", reverse_list(lst))

Reversed list: [6, 5, 4, 3, 2, 1]


In [ ]:
def remove_first_last(lst):

    return lst[1:-1]

# Example usage:
print("Removed first and last:", remove_first_last(lst))

Removed first and last: [2, 3, 4, 5]


In [ ]:
def get_first_n(lst, n):

    return lst[:n]

# Example usage:
print("First 3 elements:", get_first_n(lst, 3))

First 3 elements: [1, 2, 3]


In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

lst = [1, 2, 3, 4, 5]
n = 2
print(get_last_n(lst, n))

[4, 5]


In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage:
lst = [1, 2, 3, 4, 5, 6]
print(reverse_skip(lst))

[5, 3, 1]


In [ ]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(lst, indices))

6


In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


In [ ]:
def remove_element(lst, elem):
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    return lst

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem))

[[1], [3], [4, 5]]


In [ ]:
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(lst, elem))

3


In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
def average_nested(lst):
    total, count = 0, 0
    def helper(lst):
        nonlocal total, count
        for item in lst:
            if isinstance(item, list):
                helper(item)
            else:
                total += item
                count += 1
    helper(lst)
    return total / count if count > 0 else 0

print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


In [ ]:
import numpy as np

array1 = np.empty((2, 2))
print("Empty array (2x2):\n", array1)

array2 = np.ones((4, 2))
print("\nAll-one array (4x2):\n", array2)

array3 = np.full((3, 3), 7)
print("\nArray filled with 7 (3x3):\n", array3)

array4 = np.zeros_like(array2)
print("\nZeros array with same shape as array2:\n", array4)

array5 = np.ones_like(array2)
print("\nOnes array with same shape as array2:\n", array5)

new_list = [1, 2, 3, 4]
array6 = np.array(new_list)
print("\nConverted list to array:", array6)

Empty array (2x2):
 [[ 2.39926054e-316  0.00000000e+000]
 [ 4.96661664e-317 -1.70101448e+260]]

All-one array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array with same shape as array2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones array with same shape as array2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Converted list to array: [1 2 3 4]


In [ ]:
array7 = np.arange(10, 50)
print("\nArray from 10 to 49:\n", array7)

array8 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix from 0 to 8:\n", array8)

identity_matrix = np.eye(3)
print("\nIdentity matrix (3x3):\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array mean:", mean_value)

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nMin value:", min_value, "Max value:", max_value)

array9 = np.zeros(10)
array9[4] = 1
print("\nZero array with 5th element replaced by 1:\n", array9)

arr = [1, 2, 0, 0, 4, 0]
reversed_arr = np.flip(arr)
print("\nReversed array:", reversed_arr)

array10 = np.ones((5, 5))
array10[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", array10)

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard pattern (8x8):\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array mean: 0.4400243657453023

Min value: 0.00490820631723321 Max value: 0.994099247212987

Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array: [0 4 0 0 2 1]

2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard pattern (8x8):
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# Arrays for operations
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_result = x + y
print("\nAddition of x and y:\n", add_result)

subtract_result = x - y
print("\nSubtraction of x and y:\n", subtract_result)

multiply_result = x * 2
print("\nMultiplication of x by 2:\n", multiply_result)

square_result = np.square(x)
print("\nSquare of each element in x:\n", square_result)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product v . w:", dot_vw)
print("Dot product x . v:\n", dot_xv)
print("Dot product x . y:\n", dot_xy)

concat_xy_row = np.concatenate((x, y), axis=1)
print("\nConcatenation of x and y along row:\n", concat_xy_row)

concat_vw_col = np.vstack((v, w))
print("\nConcatenation of v and w along column:\n", concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=1)
except Exception as e:
    print("\nError during concatenation of x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product v . w: 219
Dot product x . v:
 [29 77]
Dot product x . y:
 [[19 22]
 [50 58]]

Concatenation of x and y along row:
 [[1 2 5 6]
 [3 5 7 8]]

Concatenation of v and w along column:
 [[ 9 10]
 [11 12]]

Error during concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("\nA * A^-1 (should be identity matrix):\n", identity_matrix)

#AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

# (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\nTranspose of AB:\n", AB_transpose)
print("B^T * A^T:\n", BT_AT)

#linear equations
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const_matrix = np.array([-1, -3, 9])


solution = np.linalg.solve(coeff_matrix, const_matrix)
print("\nSoln to the system of equations (x, y, z):", solution)


A * A^-1 (should be identity matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

Transpose of AB:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]

Soln to the system of equations (x, y, z): [ 2.  1. -2.]


In [ ]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()

print(f"Time taken for element-wise addition using Python lists: {end_time - start_time} seconds")

Time taken for element-wise addition using Python lists: 0.19258427619934082 seconds


In [ ]:
import numpy as np

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start_time = time.time()
result_arr = arr1 + arr2
end_time = time.time()

print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time} seconds")

Time taken for element-wise addition using NumPy arrays: 0.009543180465698242 seconds


In [ ]:
start_time = time.time()
result_mult_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()

print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")

Time taken for element-wise multiplication using Python lists: 0.11672401428222656 seconds


In [ ]:
start_time = time.time()
result_mult_arr = arr1 * arr2
end_time = time.time()

print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time} seconds")

Time taken for element-wise multiplication using NumPy arrays: 0.008559465408325195 seconds


In [ ]:
start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(1000000)])
end_time = time.time()

print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")

Time taken for dot product using Python lists: 0.1844940185546875 seconds


In [ ]:
start_time = time.time()
dot_product_arr = np.dot(arr1, arr2)
end_time = time.time()

print(f"Time taken for dot product using NumPy arrays: {end_time - start_time} seconds")


Time taken for dot product using NumPy arrays: 0.004972219467163086 seconds


In [12]:
import time
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
result_matrix_list = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)]
    for i in range(1000)
]
end_time = time.time()

print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")

Time taken for matrix multiplication using Python lists: 203.9166567325592 seconds


In [16]:
import time
import numpy as np
matrix1_arr = np.random.rand(1000, 1000)
matrix2_arr = np.random.rand(1000, 1000)

start_time = time.time()
result_matrix_arr = np.dot(matrix1_arr, matrix2_arr)
end_time = time.time()

print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time} seconds")

Time taken for matrix multiplication using NumPy arrays: 0.06636166572570801 seconds
